#!/usr/bin/env bash
# Track Omarchy rough edges.
#
#   ./lab.sh new "hyprsunset goes stale after resume"   scaffold findings/NNNN-slug.md
#   ./lab.sh list [status]                              one line per finding
#   ./lab.sh index                                      regenerate INDEX.md
#   ./lab.sh check                                      re-read upstream state via gh
#
# A finding is one markdown file in findings/ with a `---` header block.
# Only that header is machine-read; the prose below it is for humans.
set -u
REPO="$(dirname "$(readlink -f "$0")")"
cd "$REPO"

STATUSES="noted filed accepted fixed patched wontfix"

# field <file> <key> -- value from the header block, empty if absent
field() { sed -n '/^---$/,/^---$/p' "$1" | sed -n "s/^$2: *//p" | head -1; }

usage() { sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

next_id() {
  local last
  last=$(ls findings/ 2>/dev/null | sed -n 's/^\([0-9]\{4\}\).*/\1/p' | sort | tail -1)
  printf '%04d' $((10#${last:-0} + 1))
}

cmd_new() {
  [ $# -ge 1 ] || { echo "need a title" >&2; exit 1; }
  local title="$*" id slug file
  id=$(next_id)
  slug=$(printf '%s' "$title" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]\+/-/g; s/^-//; s/-$//' | cut -c1-50)
  file="findings/$id-$slug.md"
  cat > "$file" <<EOF
---
id: $id
title: $title
status: noted
area:
upstream:
patch:
found: $(date +%F)
versions: $(pacman -Q omarchy 2>/dev/null | tr '\n' ' ')
---

## What happens

## Why

## Repro

## Fix
EOF
  echo "$file"
}

cmd_list() {
  local want="${1:-}" f
  for f in findings/[0-9]*.md; do
    [ -e "$f" ] || { echo "no findings yet"; return; }
    local st; st=$(field "$f" status)
    [ -n "$want" ] && [ "$st" != "$want" ] && continue
    printf '  %-4s %-8s %-11s %s\n' "$(field "$f" id)" "$(field "$f" status)" "$(field "$f" area)" "$(field "$f" title)"
  done
}

cmd_index() {
  {
    echo "# Findings"
    echo
    echo "Regenerated by \`./lab.sh index\` — edit the files in \`findings/\`, not this table."
    echo
    echo "| # | Status | Area | Finding | Upstream | Patch |"
    echo "|---|---|---|---|---|---|"
    local f
    for f in findings/[0-9]*.md; do
      [ -e "$f" ] || continue
      local up patch
      up=$(field "$f" upstream); patch=$(field "$f" patch)
      case "$up" in
        https://github.com/*/issues/*) up="[#${up##*/}]($up)" ;;
        https://github.com/*/pull/*)   up="[PR ${up##*/}]($up)" ;;
        "")                            up="—" ;;
      esac
      [ -n "$patch" ] && patch="[\`${patch##*/}\`]($patch)" || patch="—"
      printf '| %s | %s | %s | [%s](%s) | %s | %s |\n' \
        "$(field "$f" id)" "$(field "$f" status)" "$(field "$f" area)" \
        "$(field "$f" title)" "$f" "$up" "$patch"
    done
  } > INDEX.md
  echo "INDEX.md: $(ls findings/[0-9]*.md 2>/dev/null | wc -l) finding(s)"
}

cmd_check() {
  command -v gh >/dev/null || { echo "gh not installed" >&2; exit 1; }
  local f
  for f in findings/[0-9]*.md; do
    [ -e "$f" ] || continue
    local up; up=$(field "$f" upstream)
    [ -n "$up" ] || continue
    local state
    state=$(gh issue view "$up" --json state,title --jq '.state' 2>/dev/null) \
      || state=$(gh pr view "$up" --json state --jq '.state' 2>/dev/null) \
      || state="?"
    printf '  %-4s %-8s %-7s %s\n' "$(field "$f" id)" "$(field "$f" status)" "$state" "$up"
  done
}

case "${1:-}" in
  new)   shift; cmd_new "$@" ;;
  list)  shift; cmd_list "${1:-}" ;;
  index) cmd_index ;;
  check) cmd_check ;;
  ""|-h|--help) usage ;;
  *) echo "unknown command: $1" >&2; usage 1 ;;
esac
